---
- include_tasks: repositories.yml

- include_tasks: mongodb.yml

- name: Ensure mongod is started and enabled to start at boot.
  service:
    name: mongod
    enabled: true
    state: started
  become: true
