---
# nojournal not supported for default engine
# inMemory engine seems only in Enterprise distribution
- name: Ensure mongodb4+ does not use nojournal - systemd
  become: true
  replace:
    dest: /etc/systemd/system/mongod.service
    regexp: ' --nojournal$'
    replace: ''
    backup: true
  when: mongodb_version is defined and mongodb_version|string == '4.2'
  notify:
    - reload systemd
    - restart mongo

- name: Ensure mongodb4+ does not use nojournal - config
  become: true
  template:
    src: mongo4-ramdisk.conf.j2
    dest: /usr/share/meteor/bundle/mongo-ramdisk.conf
    backup: true
    mode: '0644'
  notify:
    - restart mongo
  when: mongodb_version is defined and mongodb_version|string == '4.2'
